#!/bin/sh

# if no .py files are staged, exit
git diff --cached --name-only --diff-filter=ACM | grep -q '\.py$' || exit 0

# if .py files are staged, run lint and formatter
ruff check --fix .
ruff format .
git add -u
