# format
OUTPUT_FORMAT = 'WEBP'
OUTPUT_EXTENSION = OUTPUT_FORMAT.lower()
OUTPUT_QUALITY = 80

# size
LONG_STRIP_ASPECT_RATIO = 5/8
MAX_HEIGHT = 1920
MAX_WIDTH = 1200

# cropping
BLACK_THRESHOLD = 8
WHITE_THRESHOLD = 248
MAX_PAGE_ASPECT_RATIO = 1/5
