PREFERRED_ENCODING = 'utf-8'
FALLBACK_ENCODING = 'cp1252'
HIDDEN_FILE_ATTRS = ['h']
HIDDEN_SYSTEM_FILE_ATTRS = ['h', 's']

DESKTOP_INI_FILENAME = 'desktop.ini'
INI_ICON_KEY = 'IconResource'
INI_SHELL_SECTION = '.ShellClassInfo'

MAX_ICO_SIZE = 256
DEFAULT_ICO_SIZES = [16, 48, 256]
ICO_FILENAME = 'icon.ico'
