BINARY_BLACKLIST = {
  '.bak',
  'converter',
  'crash',
  'maintenance',
  'tool',
  'update',
}

BINARY_BY_PLATFORM = {
  '3ds': ['citra-qt', 'citra'],
  'gba': ['mgba', 'visualboyadvance-m', 'visualboyadvance'],
  'gcn': ['dolphin'],
  'n64': ['project64'],
  'nds': ['desmume', 'melonds'],
  'ps1': ['duckstation-qt-x64-releaseltcg', 'duckstation'],
  'ps2': ['pcsx2-qt', 'pcsx2'],
  'ps3': ['rpcs3'],
  'psp': ['ppssppwindows64', 'ppssppwindows', 'ppsspp'],
  'snes': ['bsnes_hd', 'snes9x'],
  'switch': ['yuzu', 'ryujinx'],
  'vita': ['vita3k'],
  'wii u': ['cemu'],
  'wii': ['dolphin'],
  'x360': ['xenia_canary', 'xenia'],
  'xbox': ['xemu'],
}

ROM_EXTS = {
  '.3ds',
  '.7z',
  '.cue',
  '.gb',
  '.gba',
  '.gbc',
  '.img',
  '.iso',
  '.n64',
  '.nds',
  '.nes',
  '.nsp',
  '.sfc',
  '.smc',
  '.smd',
  '.v64',
  '.wbfs',
  '.xci',
  '.z64',
}