# folders
FOLDER_OUTPUT_FORMAT = 'ZIP'
FOLDER_OUTPUT_EXTENSION = FOLDER_OUTPUT_FORMAT.lower()

# images
IMAGE_OUTPUT_FORMAT = 'WEBP'
IMAGE_OUTPUT_EXTENSION = IMAGE_OUTPUT_FORMAT.lower()
IMAGE_OUTPUT_QUALITY = 80
